export const MODEL_A_TOGGLE = "MODEL_A_TOGGLE";
export const MODEL_B_TOGGLE = "MODEL_B_TOGGLE";
export const MODEL_A_ALL_COUNTRY_DATA = "MODEL_A_ALL_COMPANY_DATA";
export const MODEL_A_ALL_COUNTRY_DATA_SEARCH =
  "MODEL_A_ALL_COUNTRY_DATA_SEARCH";
export const MODEL_B_US_COUNTRY_DATA = "MODEL_B_US_COUNTRY_DATA";
export const MODEL_A_CHECKBOX_STATUS_TOGGLE = "MODEL_A_CHECKBOX_STATUS_TOGGLE";
export const MODEL_B_CHECKBOX_STATUS_TOGGLE = "MODEL_B_CHECKBOX_STATUS_TOGGLE";
export const MODEL_B_ALL_COUNTRY_DATA_SEARCH =
  "MODEL_B_ALL_COUNTRY_DATA_SEARCH";
export const MODEL_C_TOGGLE = "MODEL_C_TOGGLE";
export const SAVE_DROPDOWN_LIST_DATA_TO_STORE =
  "SAVE_DROPDOWN_LIST_DATA_TO_STORE";
export const SAVE_FAMILY_DATA_TO_STORE = "SAVE_FAMILY_DATA_TO_STORE";
export const SAVE_MEMBER_DATA_TO_STORE = "SAVE_MEMBER_DATA_TO_STORE";
export const ADD_MEMBER_DATA_TO_MEMBER_LIST = "ADD_MEMBER_DATA_TO_MEMBER_LIST";
export const UPDATE_MEMBER_DATA_TO_MEMBER_LIST =
  "UPDATE_MEMBER_DATA_TO_MEMBER_LIST";
export const DELETE_MEMBER_DATA_FROM_MEMBER_LIST =
  "DELETE_MEMBER_DATA_FROM_MEMBER_LIST";
export const ADD_MEMBER_DATA_TO_DAUGHTER_MEMBER_LIST =
  "ADD_MEMBER_DATA_TO_DAUGHTER_MEMBER_LIST";
export const DELETE_MEMBER_DATA_FROM_DAUGHTER_MEMBER_LIST =
  "DELETE_MEMBER_DATA_FROM_DAUGHTER_MEMBER_LIST";
export const ADD_DAUGHTER_MEMBER_LIST = "ADD_DAUGHTER_MEMBER_LIST";
export const DELETE_DAUGHTER_MEMBER_LIST = "DELETE_DAUGHTER_MEMBER_LIST";
export const INITIALIZE_WHOLE_DATA = "INITIALIZE_WHOLE_DATA";
export const UPDATE_FAMILYID_TO_STORE = "UPDATE_FAMILYID_TO_STORE";
// export const SELECT_FAMILY_TAB_NATIVE_PLACE = "SELECT_FAMILY_TAB_NATIVE_PLACE";
// export const SELECT_FAMILY_TAB_PRESENT_PLACE = "SELECT_FAMILY_TAB_PRESENT_PLACE";
// export const SELECT_FAMILY_TAB_OCCUPATION = "SELECT_FAMILY_TAB_OCCUPATION";
